### ISSUE TITLE
Upgrade Spring Boot dependency

### ISSUE THREAD

**Issue by ocadaruma** [line/decaton#127]
- As of 2021-11-05, decaton-spring's spring-boot dependency version is `2.1.7.RELEASE`, which is way behind from boot's latest (`2.5`)
- Though decaton-spring only uses core features of boot so should be work even with newer boot version, it's better to upgrade the dependency as much as possible

**Comment by hase1108** [comment]
Hi @ocadaruma. I'd like to work on this issue. Could I get this issue assigned?

**Comment by ocadaruma** [comment]
@hase1108 Oh, thanks for your interest.
Okay then let me assign you to this issue.

**Comment by ocadaruma** [comment]
Fixed by #129
