### ISSUE TITLE
Provide BatchingProcessor as a built-in processor

### ISSUE THREAD

**Issue by ocadaruma** [line/decaton#128]
- Task batching is a common-pattern that many Decaton users often implement by their own
  * i.e. Batching several tasks of type `T` to `List<T>` and process them at once. e.g. when downstream-DB supports batching I/O (which often very efficient)
  * Batch-flushing should be done in time-based and size-based.
- So it's better to provide BatchingProcessor built-in to meet the common needs

**Comment by ryamagishi** [comment]
I'll try this issue.

**Comment by ocadaruma** [comment]
Thank you!
I assigned you.

**Comment by ocadaruma** [comment]
fixed by #139, #150
