### ISSUE TITLE
NPE in DecatonTaskRetryQueueingProcessor if RetryConfig.backoff is null

### ISSUE THREAD

**Issue by ta7uw** [line/decaton#181]
NPE occurs in `DecatonTaskRetryQueueingProcessor#process` if backoff is null.
https://github.com/line/decaton/blob/916403fac80bef5b222a661d836cb814f4aa9a53/processor/src/main/java/com/linecorp/decaton/processor/runtime/internal/DecatonTaskRetryQueueingProcessor.java#L52-L61

Should we check if `backoff` is null when building `RetryConfig` or building `Subscription` which is configured for retry processing?

https://github.com/line/decaton/blob/916403fac80bef5b222a661d836cb814f4aa9a53/processor/src/main/java/com/linecorp/decaton/processor/runtime/SubscriptionBuilder.java#L188-L201

**Comment by ocadaruma** [comment]
Nice catching. `backoff` is mandatory parameter actually but it's not validated now.

> when building RetryConfig

+1 for this.

**Comment by ta7uw** [comment]
Is it ok to use `lombok.NonNull`  in this project?

**Comment by ocadaruma** [comment]
Yes.

**Comment by ta7uw** [comment]
ok, I'll work on it
