### ISSUE TITLE
Subscription could be killed by RebalanceInProgressException

### ISSUE THREAD

**Issue by ocadaruma** [line/decaton#201]
- Decaton swallows some exceptions thrown from offset-commit on partition revocations, as by default, Decaton doesn't consider offset-commit failures as fatal one because process-duplication by commit failures are "normal" behavior which implementer should care about anyways
  * https://github.com/line/decaton/blob/v6.3.1/processor/src/main/java/com/linecorp/decaton/processor/runtime/ProcessorSubscription.java#L83-L84
- After https://github.com/apache/kafka/pull/7312, commitSync now could throw RebalanceInProgressException, which currently Decaton doesn't catch

**Comment by mauhiz** [comment]
Does that happen regardless of cooperative rebalancing?

**Comment by rfkm** [comment]
Our project that encountered this problem did not use cooperative rebalancing.
