### ISSUE TITLE
ProcessorUnit processes tasks without waiting scheduledTime on shutdown

### ISSUE THREAD

**Issue by ocadaruma** [line/decaton#26]
Scenario:

1. task X (scheduledTime = now + 100sec) is in ProcessorUnit's queue 
2. ProcessorSubscription#close()
    * ProcessosUnit#close() =>
    * ProcessPipeline#close() =>
    * ExecutionScheduler#close() => terminateLatch.countDown()
3. ExecutionScheduler#schedule() returns immediately for task X without waiting 100sec
4. task X is passed to DecatonProcessor

**Comment by yifu-yang** [comment]
Hi ,I am trying to solve the issue ,I want to know that if this happens when the job need retry on the consumer side ?

**Comment by ocadaruma** [comment]
@yifu-yang Thank you for your interest.

This issue happens when Decaton's scheduled execution feature is utilized.
As you may know, scheduled execution is like below:

- Decaton enqueues consumed tasks to ProcessorUnit's executor queue
https://github.com/line/decaton/blob/master/processor/src/main/java/com/linecorp/decaton/processor/runtime/ProcessorUnit.java#L55
- If [TaskMetadata#scheduledTimeMillis](https://github.com/line/decaton/blob/master/processor/src/main/java/com/linecorp/decaton/processor/TaskMetadata.java#L61) is set, Decaton waits for a while before passing the task to DecatonProcessor.

And since Decaton's retry queueing is based on scheduled execution, the issue can be occurred when a task is retried as you mentioned.

But we found that this issue is already solved by https://github.com/line/decaton/pull/32, which made ProcessPipeline not to pass a task to processor if pipeline is already closed.

Then let me close this issue.
Thank you again.
