### ISSUE TITLE
Change default value of max.pending.records

### ISSUE THREAD

**Issue by kawamuray** [line/decaton#37]
There was a case of batching consumer that was experiencing low throughput due to too small default max.pending.records caused frequently pause/resume loop and lowering throughput.
We set it conservatively low to avoid causing high memory pressure by default setting expecting the case where average record size is large, but maybe we can default much higher expecting in most cases record size is not so big and there's more likelihood of people get benefit of high throughput with out of the box setup.

**Comment by ocadaruma** [comment]
Another reasoning:

- Currently, we set consumer's `max.poll.records` to at most `100` here
  * https://github.com/line/decaton/blob/master/processor/src/main/java/com/linecorp/decaton/processor/runtime/internal/ConsumerSupplier.java#L33
- This means, with default max.pending.records `100`, Decaton could pause a partition easily when single `poll()` returns 100 records

**Comment by from-unknown** [comment]
I'll try this issue.

**Comment by kawamuray** [comment]
Close by #143
