### ISSUE TITLE
ERROR logged when using ProcessorSubscription as a Runnable

### ISSUE THREAD

**Issue by mauhiz** [line/decaton#62]
Since #53 `ProcessorSubscription.commitCompletedOffsets` will print an ERROR log when the `ProcessorSubscription` is run as a Runnable (e.g. submitted to an ExecutorService) rather than a Thread.
The assumption (`Thread.currentThread == this`) is not valid in that case.

The log is harmless but noisy.
I am not sure who else uses ProcessorSubscription in this way but it does not seem unreasonable (e.g. to get metrics by thread group) so I think the best way is to just remove the extra check

**Comment by kawamuray** [comment]
Thanks for reporting!

This is indeed a case that we couldn't expected at the time we implemented that assertion, but using `ProcessorSubscription` just as a `Runnable` should be an valid option.
I've attempted to fix the assertion rather than removing it completely at #63
